host: 0.0.0.0
exclude: ["Rakefile", "Gemfile*", "vendor", "_site", "circle.yml"]
production_url : http://gosyujin.github.io
permalink: /:year/:month/:day/:title

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [tables,with_toc_data]

title : kk_Atakaの日記
author :
  name : kk_Ataka
  email : kk_ataka@ring.skr.jp
  github : gosyujin
  twitter : kk_Ataka
disqus :
  short_name : kkataka
google :
  tracking_id : 'UA-34929069-1'
