title                  = "kk_Atakaの日記"
language               = "jp"
languageCode           = "jp"
defaultContentLanguage = "jp"

baseURL      = "/"
contentDir   = "md"
# publishDir = "_site"
ignoreFiles  = ["\\var/$"]

googleAnalytics = "UA-34929069-1"

footnoteAnchorPrefix       = "#"
footnoteReturnLinkContents = "##"

paginate              = 10
paginatePath          ="page"
preserveTaxonomyNames = true

pygmentsUseClasses            = true
pygmentsCodefences            = true
pygmentsCodeFencesGuessSyntax = true
# pygmentsOptions             = "linenos=inline"
# $ hugo gen chromastyles --style monokai > syntax.css

[blackfriday]
fractions     = false
#   taskLists = false

[taxonomies]
  tag        = "tags"

[permalinks]
  posts = "/:year/:month/:day/:slug"

[frontmatter]
  date  = [":filename", ":default"]

[[menu.main]]
  identifier = "about"
  name       = "About"
  url        = "/about/"
  weight     = 1
[[menu.main]]
  identifier = "archives"
  name       = "Archives"
  url        = "/"
  weight     = 2
[[menu.main]]
  identifier = "tags"
  name       = "Tags"
  url        = "/tags/"
  weight     = 3

[params]
