title                  = "kk_Atakaの日記"
language               = "jp"
languageCode           = "jp"
defaultContentLanguage = "jp"

baseURL      = "/"
contentDir   = "md"
# publishDir = "_site"
ignoreFiles  = ["\\var/$"]

googleAnalytics = ""

footnoteAnchorPrefix       = "#"
footnoteReturnLinkContents = "##"

paginate              = 10
paginatePath          ="page"
preserveTaxonomyNames = true

pygmentsUseClasses            = true
pygmentsCodefences            = true
pygmentsCodeFencesGuessSyntax = true
# pygmentsOptions             = "linenos=inline"
# $ hugo gen chromastyles --style monokai > syntax.css

[blackfriday]
fractions     = false
#   taskLists = false

[taxonomies]
  tag        = "tags"

[permalinks]
  posts = "/:year/:month/:day/:slug"

[frontmatter]
  date  = [":filename", ":default"]

[[menu.main]]
  name   = "Archives"
  url    = "/"
  weight = 1
[[menu.main]]
  name   = "Tags"
  url    = "/tags/"
  weight = 2

[params]
